//Plank John


var json = {
	"data1": {
		"fear": ["Fear Level: ", "Psalm 144:1"],
		"apocalypse": ["Apocalypse: ", "Zombie"],
		"firearm": ["Firearm: ", "check"],
		"ammo": ["Ammo: ", "check"],
        "melee": ["Melee Weapon: ", "check"],
		"canned": ["Canned: ", "check"],
		"water": ["Water: ", "check"],
		"chain":["Chain Mesh Suit: ", "uncheck"],
		"map": ["Topographical: ", "check"],
		"leatherman": ["Leatherman: ", "check"],
		"rucksack": ["Rucksack: ", "check"],
		"boots": ["Boots", "check"],
		"matches": ["Matches: ", "check"],
		"p38": ["P38: ", "check"],
		"intestinal": ["Intestinal Fortitude: ", "check"],
		"item": ["Item: ", "Zombie Spray"],
		"date": ["World Ended: ", "2020-05-24"],
		"email": ["Email: ", "fidleromthegreen@yahoo.com"],
		"comments": ["Comments", "Suck it cruel world"],
		"readiness": ["Readiness", "11"]
	},
	"data2": {
		"fear": ["Fear Level: ", "Are you kidding me?"],
		"apocalypse": ["Apocalypse: ", "Natural"],
		"firearm": ["Firearm: ", "check"],
		"ammo": ["Ammo: ", "check"],
        "melee": ["Melee Weapon: ", "uncheck"],
		"canned": ["Canned: ", "check"],
		"water": ["Water: ", "uncheck"],
		"chain":["Chain Mesh Suit: ", "uncheck"],
		"map": ["Topographical: ", "check"],
		"leatherman": ["Leatherman: ", "check"],
		"rucksack": ["Rucksack: ", "check"],
		"boots": ["Boots", "check"],
		"matches": ["Matches: ", "check"],
		"p38": ["P38: ", "check"],
		"intestinal": ["Intestinal Fortitude: ", "check"],
		"item": ["Item: ", "Bible"],
		"date": ["World Ended: ", "2015-05-24"],
		"email": ["Email: ", "momma@yahoo.com"],
		"comments": ["Comments", "To live is to die"],
		"readiness": ["Readiness", "8"]
	},
	"data3": {
		"fear": ["Fear Level: ", "Opps I crapped my pants"],
		"apocalypse": ["Apocalypse: ", "Atomic"],
		"firearm": ["Firearm: ", "check"],
		"ammo": ["Ammo: ", "check"],
        "melee": ["Melee Weapon: ", "check"],
		"canned": ["Canned: ", "uncheck"],
		"water": ["Water: ", "check"],
		"chain":["Chain Mesh Suit: ", "uncheck"],
		"map": ["Topographical: ", "check"],
		"leatherman": ["Leatherman: ", "check"],
		"rucksack": ["Rucksack: ", "uncheck"],
		"boots": ["Boots", "check"],
		"matches": ["Matches: ", "uncheck"],
		"p38": ["P38: ", "check"],
		"intestinal": ["Intestinal Fortitude: ", "check"],
		"item": ["Item: ", "Sunscreen"],
		"date": ["World Ended: ", "2014-05-23"],
		"email": ["Email: ", "dork@yahoo.com"],
		"comments": ["Comments", "Rather be fishing"],
		"readiness": ["Readiness", "4"]		
	}
};